development:
  adapter: postgresql
  encoding: unicode
  database: my_fb_picts_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: my_fb_picts_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: my_fb_picts_production
  pool: 5
